server: 
  port: 10002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: 1234
  jpa: 
    database: mysql
    show-sql: true
