server:
  port: 10012
spring:
  application:
    name: tensquare-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /bagatheringse/**
      serviceId: tensquare-gathering
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
    tensquare-search:
      path: /search/**
      serviceId: tensquare-search
